import { readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const projectRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const sourcePath = resolve(projectRoot, "common.css");
const source = await readFile(sourcePath, "utf8");
const marker = "/** generated by https://github.com/voderl/font-slice */";
const sections = source
  .split(new RegExp(`(?=${marker.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")})`, "g"))
  .map((section) => section.trim())
  .filter(Boolean);

if (sections.length !== 4) {
  throw new Error(`Expected 4 generated weight sections, found ${sections.length}.`);
}

for (const section of sections) {
  const weights = [...section.matchAll(/font-weight:\s*(\d+);/g)].map((match) => Number(match[1]));
  const uniqueWeights = [...new Set(weights)];
  if (weights.length !== 96 || uniqueWeights.length !== 1) {
    throw new Error(`Invalid section: faces=${weights.length}, weights=${uniqueWeights.join(",")}.`);
  }

  const weight = uniqueWeights[0];
  await writeFile(resolve(projectRoot, `common-${weight}.css`), `${section}\n`, "utf8");
  console.log(`generated common-${weight}.css (${weights.length} faces)`);
}
